CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL,
  uid INT NOT NULL
);

CREATE TABLE IF NOT EXISTS logs (
  id SERIAL PRIMARY KEY,
  time TIME NOT NULL DEFAULT CURRENT_TIME,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  uid TEXT NOT NULL
);
